{% set name = "proselint" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f90d5e3414928194be23efdf1e3e821bbb79279a598cf1710b29977029c4897

build:
  number: 0
  entry_points:
    - proselint = proselint.command_line:proselint
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - click
    - future
    - python
    - six

test:
  imports:
    - proselint
    - proselint.checks
    - proselint.checks.airlinese
    - proselint.checks.annotations
    - proselint.checks.archaism
    - proselint.checks.cliches
    - proselint.checks.consistency
    - proselint.checks.corporate_speak
    - proselint.checks.cursing
    - proselint.checks.dates_times
    - proselint.checks.hedging
    - proselint.checks.hyperbole
    - proselint.checks.jargon
    - proselint.checks.lexical_illusions
    - proselint.checks.lgbtq
    - proselint.checks.links
    - proselint.checks.malapropisms
    - proselint.checks.misc
    - proselint.checks.mixed_metaphors
    - proselint.checks.mondegreens
    - proselint.checks.needless_variants
    - proselint.checks.nonwords
    - proselint.checks.oxymorons
    - proselint.checks.psychology
    - proselint.checks.redundancy
    - proselint.checks.security
    - proselint.checks.sexism
    - proselint.checks.skunked_terms
    - proselint.checks.spelling
    - proselint.checks.terms
    - proselint.checks.typography
    - proselint.checks.uncomparables
    - proselint.checks.weasel_words
  commands:
    - proselint --help

about:
  home: http://github.com/amperser/proselint
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A linter for prose.

extra:
  recipe-maintainers:
    - CJ-Wright
