travis:
  secure:
    BINSTAR_TOKEN: JfkwUynrslQj/RUtUePgL7YpLdwd4lkxazwUkGxaZNilHdJGsqP99x+EXdlxh/s33kW9lYXxq7H/RvR5TROxtGfYtDqkejckC3zeVJCOWOxiTfmKDAlyRXRESrPTQvI9+Tn50OQZP1g9+xTqQKpw63NAIGHgRRoyAQNTIsUxi9IcaCCzNltWXaKPnBRTy5ofuRjUKNUDlh8v3emOhUEJifWJ9KQoGBpURZLeqD3N1AMRq/sn2Hj7WBA3Puc6Fu+Ydg83xU1kkShMvIfxQHz10IpIu7IxvfjTBRjUtRs+yVHDmkGdjajmHiUvGIyMUnX+pUHdZGqmU8QYdTckiGaC/YpK328mJfpRZ+P/P3/IR2uwMm65HjeyuI2sUnU9idZPBJWi0D530rh8lFrNJ4+bMKGfnC4aFojLoWMQc7EB/Y6ENgHT/rly0nP7hppJAnK9j17fwkX588LJNfl9Dq41zhyVF5IeIfTd/NZ72AkIjXxnngZq2tXGf8EoyZ3KuepiaaHiMPIjib/9qtTF0nN92MEJPySneG9pXNFFZzcjsqfgfoQ1nsGW9aLNKOyH7K2ddes+HbpKkrUI06pixDMe5/Q6nb8griSSYahYg9DaLZ2RqgMi5thraGUnfiG2R9B5MVrliztE93iIPmPB7RDo/HtDsLIuftOTcRrqqURZYUg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
